baseURL = 'https://starfield-data.pages.dev/'
languageCode = 'en-us'
title = "Starfield Data"
theme = 'beautifulhugo'
googleAnalytics = 'G-MS58PM494H'

[params]
  disclaimerText = 'This website is a personal project. This site is not affiliated with, nor endorsed by Bethesda.'
[menu]
[[menu.main]]
    name = 'Items'
    pageRef = '/items'
    weight = 10
[[menu.main]]
    name = 'Research'
    pageRef = '/research'
    weight = 20
[[menu.main]]
    name = 'Locations'
    pageRef = '/locations'
    weight = 30
[[menu.main]]
    name = 'Data'
    pageRef = '/data'
    weight = 90
[[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 99
[[menu.main]]
    name = 'Bookmarks'
    pageRef = '/bookmarks'
    weight = 100
[[menu.main]]
    name = 'Help'
    pageRef = '/help'
    weight = 105

[taxonomies]
  # defaults
  category = 'categories'
  tag = 'tags'

  # Custom
  # system = 'systems'
